export const continents = [
    {
      id: "asia",
      name: "Ásia",
      call: "O maior dos continentes.",
      callImage: "/asia/call.png",
      bannerImage: "/asia/banner.png",
      about:
        "A Ásia é o maior dos continentes, tanto em área como em população. Abrange um terço das partes sólidas da superfície da Terra e é responsável por abrigar quase três quintos da população mundial. A Ásia faz fronteira no lado ocidental com a África e com a Europa, e no lado oriental com o oceano Pacífico, a Oceania e, em menor proporção, com a América do Norte, pelo Estreito de Bering.",
      countries: 50,
      languages: 2300,
      cities100: 51,
      cities: [
        {
          id: "hong_kong",
          name: "Hong Kong",
          image: "/asia/hong_kong.png",
          country: "China",
          code: "cn",
        },
        {
          id: "bangkok",
          name: "Bangkok",
          image: "/asia/bangkok.png",
          country: "Tailândia",
          code: "th",
        },
        {
          id: "macau",
          name: "Macau",
          image: "/asia/macau.png",
          country: "China",
          code: "cn",
        },
        {
          id: "singapore",
          name: "Singapura",
          image: "/asia/singapore.png",
          country: "Singapura",
          code: "sg",
        },
        {
          id: "dubai",
          name: "Dubai",
          image: "/asia/dubai.png",
          country: "Emirados Árabes Unidos",
          code: "ae",
        },
        {
          id: "kuala_lumpur",
          name: "Kuala Lumpur",
          image: "/asia/kuala_lumpur.png",
          country: "Malásia",
          code: "my",
        },
        {
          id: "istanbul",
          name: "Istanbul",
          image: "/asia/istanbul.png",
          country: "Turquia",
          code: "tr",
        },
        {
          id: "delhi",
          name: "Deli",
          image: "/asia/delhi.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "antalya",
          name: "Antália",
          image: "/asia/antalya.png",
          country: "Turquia",
          code: "tr",
        },
        {
          id: "shenzhen",
          name: "Shenzhen",
          image: "/asia/shenzhen.png",
          country: "China",
          code: "cn",
        },
        {
          id: "mumbai",
          name: "Bombaim",
          image: "/asia/mumbai.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "phuket",
          name: "Phuket",
          image: "/asia/phuket.png",
          country: "Tailândia",
          code: "th",
        },
        {
          id: "tokyo",
          name: "Tóquio",
          image: "/asia/tokyo.png",
          country: "Japão",
          code: "jp",
        },
        {
          id: "pattaya",
          name: "Pattaya",
          image: "/asia/pattaya.png",
          country: "Tailândia",
          code: "th",
        },
        {
          id: "taipei",
          name: "Taipé",
          image: "/asia/taipei.png",
          country: "Taiwan",
          code: "tw",
        },
        {
          id: "mecca",
          name: "Mecca",
          image: "/asia/mecca.png",
          country: "Arábia Saudita",
          code: "sa",
        },
        {
          id: "guangzhou",
          name: "Cantão",
          image: "/asia/guangzhou.png",
          country: "China",
          code: "cn",
        },
        {
          id: "medina",
          name: "Medina",
          image: "/asia/medina.png",
          country: "Arábia Saudita",
          code: "sa",
        },
        {
          id: "seoul",
          name: "Seul",
          image: "/asia/seoul.png",
          country: "Coreia do Sul ",
          code: "kr",
        },
        {
          id: "agra",
          name: "Agra",
          image: "/asia/agra.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "osaka",
          name: "Osaka",
          image: "/asia/osaka.png",
          country: "Japão",
          code: "jp",
        },
        {
          id: "shanghai",
          name: "Xangai",
          image: "/asia/shanghai.png",
          country: "China",
          code: "cn",
        },
        {
          id: "ho_chi_minh",
          name: "Ho Chi Minh",
          image: "/asia/ho_chi_minh.png",
          country: "Vietnã",
          code: "vn",
        },
        {
          id: "denpasar",
          name: "Denpasar",
          image: "/asia/denpasar.png",
          country: "Indonésia",
          code: "id",
        },
        {
          id: "chennai",
          name: "Chennai",
          image: "/asia/chennai.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "johor_bahru",
          name: "Johor Bahru",
          image: "/asia/johor_bahru.png",
          country: "Malásia",
          code: "my",
        },
        {
          id: "jaipur",
          name: "Jaipur",
          image: "/asia/jaipur.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "riyadh",
          name: "Riad",
          image: "/asia/riyadh.png",
          country: "Arábia Saudita",
          code: "sa",
        },
        {
          id: "ha_noi",
          name: "Hanói",
          image: "/asia/ha_noi.png",
          country: "Vietnã",
          code: "vn",
        },
        {
          id: "jakarta",
          name: "Jacarta",
          image: "/asia/jakarta.png",
          country: "Indonésia",
          code: "id",
        },
        {
          id: "ha_long",
          name: "Ha Long",
          image: "/asia/ha_long.png",
          country: "Vietnã",
          code: "vn",
        },
        {
          id: "beijing",
          name: "Pequim",
          image: "/asia/beijing.png",
          country: "China",
          code: "cn",
        },
        {
          id: "jerusalem",
          name: "Jerusalem",
          image: "/asia/jerusalem.png",
          country: "Israel",
          code: "il",
        },
        {
          id: "dammam",
          name: "Damã",
          image: "/asia/dammam.png",
          country: "Arábia Saudita",
          code: "sa",
        },
        {
          id: "penang_island",
          name: "Ilha de Penang",
          image: "/asia/penang_island.png",
          country: "Malásia",
          code: "my",
        },
        {
          id: "kyoto",
          name: "Quioto",
          image: "/asia/kyoto.png",
          country: "Japão",
          code: "jp",
        },
        {
          id: "zhuhai",
          name: "Zhuhai",
          image: "/asia/zhuhai.png",
          country: "China",
          code: "cn",
        },
        {
          id: "chiang_mai",
          name: "Chiang Mai",
          image: "/asia/chiang_mai.png",
          country: "Tailândia",
          code: "th",
        },
        {
          id: "kolkata",
          name: "Calcutá",
          image: "/asia/kolkata.png",
          country: "Índia",
          code: "in",
        },
        {
          id: "cebu",
          name: "Cebu",
          image: "/asia/cebu.png",
          country: "Philippines",
          code: "ph",
        },
        {
          id: "tel_aviv",
          name: "Telavive",
          image: "/asia/tel_aviv.png",
          country: "Israel",
          code: "il",
        },
        {
          id: "guilin",
          name: "Guilin",
          image: "/asia/guilin.png",
          country: "China",
          code: "cn",
        },
        {
          id: "mugla",
          name: "Mugla",
          image: "/asia/mugla.png",
          country: "Turquia",
          code: "tr",
        },
        {
          id: "chiba",
          name: "Chiba",
          image: "/asia/chiba.png",
          country: "Japão",
          code: "jp",
        },
        {
          id: "da_nang",
          name: "Da Nang",
          image: "/asia/da_nang.png",
          country: "Vietnã",
          code: "vn",
        },
        {
          id: "batam",
          name: "Batam",
          image: "/asia/batam.png",
          country: "Indonésia",
          code: "id",
        },
        {
          id: "fukuoka",
          name: "Fukuoka",
          image: "/asia/fukuoka.png",
          country: "Japão",
          code: "jp",
        },
        {
          id: "abu_dhabi",
          name: "Abu Dhabi",
          image: "/asia/abu_dhabi.png",
          country: "Emirados Árabes Unidos",
          code: "ae",
        },
        {
          id: "jeju",
          name: "Jeju",
          image: "/asia/jeju.png",
          country: "Coreia do Sul ",
          code: "kr",
        },
        {
          id: "krabi",
          name: "Krabi",
          image: "/asia/krabi.png",
          country: "Tailândia",
          code: "th",
        },
        {
          id: "bangalore",
          name: "Bangalore",
          image: "/asia/bangalore.png",
          country: "Índia",
          code: "in",
        },
      ],
    },
    {
      id: "europe",
      name: "Europa",
      call: "O continente mais antigo.",
      callImage: "/europe/call.png",
      bannerImage: "/europe/banner.png",
      about:
        "A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mar Cáspio, o Cáucaso, e o mar Negro a sudeste",
      countries: 50,
      languages: 60,
      cities100: 29,
      cities: [
        {
          id: "london",
          name: "Londres",
          image: "/europe/london.png",
          country: "Reino Unido",
          code: "gb",
        },
        {
          id: "paris",
          name: "Paris",
          image: "/europe/paris.png",
          country: "França",
          code: "fr",
        },
        {
          id: "roma",
          name: "Roma",
          image: "/europe/roma.png",
          country: "Itália",
          code: "it",
        },
        {
          id: "praga",
          name: "Praga",
          image: "/europe/praga.png",
          country: "República Tcheca",
          code: "cz",
        },
        {
          id: "amsterdam",
          name: "Amsterdã",
          image: "/europe/amsterdam.png",
          country: "Holanda",
          code: "nl",
        },
        {
          id: "barcelona",
          name: "Barcelona",
          image: "/europe/barcelona.png",
          country: "Espanha",
          code: "es",
        },
        {
          id: "milan",
          name: "Milão",
          image: "/europe/milan.png",
          country: "Itália",
          code: "it",
        },
        {
          id: "vienna",
          name: "Viena",
          image: "/europe/vienna.png",
          country: "Austria",
          code: "at",
        },
        {
          id: "berlin",
          name: "Berlin",
          image: "/europe/berlin.png",
          country: "Alemanha",
          code: "de",
        },
        {
          id: "athens",
          name: "Atenas",
          image: "/europe/athens.png",
          country: "Grécia",
          code: "gr",
        },
        {
          id: "moscow",
          name: "Moscou",
          image: "/europe/moscow.png",
          country: "Rússia",
          code: "ru",
        },
        {
          id: "venice",
          name: "Veneza",
          image: "/europe/venice.png",
          country: "Itália",
          code: "it",
        },
        {
          id: "madrid",
          name: "Madri",
          image: "/europe/madrid.png",
          country: "Espanha",
          code: "es",
        },
        {
          id: "dublin",
          name: "Dublin",
          image: "/europe/dublin.png",
          country: "Irlanda",
          code: "ie",
        },
        {
          id: "florence",
          name: "Florença",
          image: "/europe/florence.png",
          country: "Itália",
          code: "it",
        },
        {
          id: "munich",
          name: "Munique",
          image: "/europe/munich.png",
          country: "Alemanha",
          code: "de",
        },
        {
          id: "saint_petersburg",
          name: "São Petersburgo",
          image: "/europe/saint_petersburg.png",
          country: "Rússia",
          code: "ru",
        },
        {
          id: "brussels",
          name: "Bruxelas",
          image: "/europe/brussels.png",
          country: "Bélgica",
          code: "be",
        },
        {
          id: "budapest",
          name: "Budapeste",
          image: "/europe/budapest.png",
          country: "Hungria",
          code: "hu",
        },
        {
          id: "lisbon",
          name: "Lisboa",
          image: "/europe/lisbon.png",
          country: "Portugal",
          code: "pt",
        },
        {
          id: "heraklion",
          name: "Iráklio",
          image: "/europe/heraklion.png",
          country: "Grécia",
          code: "gr",
        },
        {
          id: "copenhagen",
          name: "Copenhage",
          image: "/europe/copenhagen.png",
          country: "Dinamarca",
          code: "dk",
        },
        {
          id: "krakow",
          name: "Cracóvia",
          image: "/europe/krakow.png",
          country: "Polônia",
          code: "pl",
        },
        {
          id: "warsaw",
          name: "Varsóvia",
          image: "/europe/warsaw.png",
          country: "Polônia",
          code: "pl",
        },
        {
          id: "frankfurt",
          name: "Frankfurt",
          image: "/europe/frankfurt.png",
          country: "Alemanha",
          code: "de",
        },
        {
          id: "stockholm",
          name: "Estocolmo",
          image: "/europe/stockholm.png",
          country: "Suécia",
          code: "se",
        },
        {
          id: "nice",
          name: "Nice",
          image: "/europe/nice.png",
          country: "França",
          code: "fr",
        },
        {
          id: "porto",
          name: "Porto",
          image: "/europe/porto.png",
          country: "Portugal",
          code: "pt",
        },
        {
          id: "rhodes",
          name: "Rodes",
          image: "/europe/rhodes.png",
          country: "Grécia",
          code: "gr",
        },
      ],
    },
    {
      id: "america",
      name: "América",
      call: "O novo continente.",
      callImage: "/america/call.png",
      bannerImage: "/america/banner.png",
      about:
        "América é o continente localizado no hemisfério ocidental e que se estende, no sentido norte-sul, desde o oceano Ártico até o cabo Horn, ao longo de cerca de 15 mil quilômetros. O seu extremo oriental insular (não continental) encontra-se na Groenlândia, o Nordostrundingen, enquanto o ocidental localiza-se nas Aleutas. Já os extremos continentais (não insulares) são o cabo Príncipe de Gales, o extremo ocidental, no Alasca, e a ponta do Seixas, extremo oriental, no estado brasileiro da Paraíba.",
      countries: 35,
      languages: 8,
      cities100: 13,
      cities: [
        {
          id: "new_york",
          name: "Nova Iorque",
          image: "/america/new_york.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "miami",
          name: "Miami",
          image: "/america/miami.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "los_angeles",
          name: "Los Angeles",
          image: "/america/los_angeles.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "las_vegas",
          name: "Las Vegas",
          image: "/america/las_vegas.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "cancun",
          name: "Cancún",
          image: "/america/cancun.png",
          country: "México",
          code: "us",
        },
        {
          id: "orlando",
          name: "Orlando",
          image: "/america/orlando.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "toronto",
          name: "Toronto",
          image: "/america/toronto.png",
          country: "Canadá",
          code: "ca",
        },
        {
          id: "vancouver",
          name: "Vancouver",
          image: "/america/vancouver.png",
          country: "Canadá",
          code: "ca",
        },
        {
          id: "san_francisco",
          name: "São Francisco",
          image: "/america/san_francisco.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "honolulu",
          name: "Honolulu",
          image: "/america/honolulu.png",
          country: "Estados Unidos",
          code: "us",
        },
        {
          id: "buenos_aires",
          name: "Buenos Aires",
          image: "/america/buenos_aires.png",
          country: "Argentina",
          code: "ar",
        },
        {
          id: "lima",
          name: "Lima",
          image: "/america/lima.png",
          country: "Peru",
          code: "pe",
        },
        {
          id: "rio_de_janeiro",
          name: "Rio de Janeiro",
          image: "/america/rio_de_janeiro.png",
          country: "Brasil",
          code: "br",
        },
      ],
    },
    {
      id: "africa",
      name: "África",
      call: "O continente mais diverso.",
      callImage: "/africa/call.png",
      bannerImage: "/africa/banner.png",
      about:
        "A África é o terceiro continente mais extenso (depois da Ásia e da América) com cerca de 30 milhões de quilômetros quadrados, cobrindo 20,3% da área total da terra firme do planeta. É o segundo continente mais populoso da Terra (atrás da Ásia) com cerca de um bilhão de pessoas (estimativa para 2005[1]), representando cerca de um sétimo da população mundial, e 54 países independentes. Tem se transformado na ultima década em uma continente cada vez mais católico.",
      countries: 54,
      languages: 3000,
      cities100: 4,
      cities: [
        {
          id: "cairo",
          name: "Cairo",
          image: "/africa/cairo.png",
          country: "Egito",
          code: "eg",
        },
        {
          id: "johannesburg",
          name: "Johannesburg",
          image: "/africa/johannesburg.png",
          country: "África do Sul",
          code: "za",
        },
        {
          id: "marrakech",
          name: "Marrakech",
          image: "/africa/marrakech.png",
          country: "Marrocos",
          code: "ma",
        },
        {
          id: "hurghada",
          name: "Hurghada",
          image: "/africa/hurghada.png",
          country: "Egito",
          code: "eg",
        },
      ],
    },
    {
      id: "oceania",
      name: "Oceânia",
      call: "O continente das ilhas.",
      callImage: "/oceania/call.png",
      bannerImage: "/oceania/banner.png",
      about:
        "Oceânia é um continente composto por vários grupos de ilhas do oceano Pacífico (Polinésia, Melanésia e Micronésia). O termo Oceania foi criado em 1831 pelo explorador francês Dumont d'Urville. O termo é usado hoje em vários idiomas para designar uma região geográfica e política que compreende o continente da Austrália e ilhas do Oceano Pacífico adjacentes.",
      countries: 16,
      languages: 18,
      cities100: 3,
      cities: [
        {
          id: "sydney",
          name: "Sydney",
          image: "/oceania/sydney.png",
          country: "Austrália",
          code: "au",
        },
        {
          id: "melbourne",
          name: "Melbourne",
          image: "/oceania/melbourne.png",
          country: "Austrália",
          code: "au",
        },
        {
          id: "auckland",
          name: "Auckland",
          image: "/oceania/auckland.png",
          country: "Nova Zelândia",
          code: "nz",
        },
      ],
    },
  ];